import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navItems = [{
    name: 'Order',
    href: '/'
  }, {
    name: 'Article',
    href: '/article'
  }]
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="w-full h-12 flex items-center px-12">
        <div>
          <h1>rimraf cqrs</h1>
        </div>
        <div className="flex-grow flex space-x-4 justify-end">
          {navItems.map((i) => (
            <Link href={i.href} key={i.name}>
              <p>{i.name}</p></Link>
          ))}
        </div>
      </div>
        {children}</body>
    </html>
  )
}
